# Generated by Django 5.2.3 on 2025-07-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_genero_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('tapa', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
