# Generated by Django 5.2.3 on 2025-07-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_biblia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='biblia',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='biblia',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='biblia',
            name='editorial',
            field=models.CharField(default='Sin editorial', max_length=100),
        ),
        migrations.AlterField(
            model_name='biblia',
            name='tapa',
            field=models.CharField(default='desconocida', max_length=50),
        ),
        migrations.AlterField(
            model_name='biblia',
            name='version',
            field=models.CharField(default='Sin version', max_length=50),
        ),
    ]
